language: cpp

compiler:
  - gcc
  - clang

os: linux

addons:
  apt:
    packages:
      - cmake
      - catch

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1 test_includer
  - ./test_includer
